Feature/refatoracao
fabuniprojecaotag/npj-backend pull request #22
Opened 2024-10-12 01:29 UTC by RafaelAguiarRodrigues

Nesta branch foi trabalhada principalmente a questão da reusabilidade e escalabilidade de código, além de alguns itens como:

- adicionado o contexto (prefixo da requisição) "/api" nas configurações dos arquivos;
- testes improvisados (não precisos) para agilizar e garantir que a repository não foi comprometida;
- upgrade na versão do spring boot para 3.3.3 (atualmente existe a 3.3.4)
- criação do ambiente de testes para não haver a necessidade de de mockar as respostas do banco e preparar o back para futuros testes de integração;
- adicionado alguns construtores via lombok (Allargs e Noargs);
- adicionado alguns construtores para testes (completos);
- renomeação dos DTOs min para list;
- renomeação da interface FirestoreRepository para BaseCRUDRepository;
- generalização do CRUD nas Services e nas Controllers (repository não é necessário por hora);
- criação de IDs customizados para todos os módulos exceto Usúarios (lógica unica);

Considerações/Pontos de melhoria:

- Adicionar um RowMapper ou Mapstruct para lidar com a conversão de DTOs para objetos json (ou map de object string) antes de enviar para o banco para evitar castings explícitos como observados em Repository e Utils;
- Separar as camadas (Model e DTO) em todas as requisições (principalmente se não for utilizados, nenhum mapper)
- Algumas funções das Utils podem voltar a ser estaticas;
- Nem todos os endpoints foram testados, porém a maior parte funciona, necessário criar testes unitários para todos (recomendavel: 80% de cobertura);
- Possivelmente algumas menores correções possam ser feitas;
- Possibilidade de remover os prefixos "ROLE_" nas authorities;
- Evoluir o tratamento de exceptions globais;

2024-10-24 18:31 UTC, jonatasmateus commented
Iniciando revisão da PR.

2024-10-24 18:52 UTC, jonatasmateus commented on src/main/java/com/uniprojecao/fabrica/gprojuridico/dto/body/UpdateBodyDTO.java
Faltou o modificador de acesso `private` nos campos para assegurar que as classes do sistema que forem interagir com esta classe apenas interajam através dos métodos GETTERs e SETTERs.

2024-10-24 19:02 UTC, jonatasmateus commented on src/main/java/com/uniprojecao/fabrica/gprojuridico/repositories/FirestoreRepositoryImpl.java
> +        firestore.collection(collectionName).document(recordId).update(data);
O método `getProcessedAndValidDataToInsertAsMap()` deve permanecer para evitar que hosts como front-end web enviem corpo de dados com campos inválidos.

2024-10-24 19:03 UTC, jonatasmateus commented on pom.xml
> +        <!-- JUnit 5 -->
A dependência **spring-security-test** já vem com as dependências do JUnit 5. Ao menos que haja uma necessidade específica, é redudante explicitar a adição da dependência no arquivo.

2024-10-24 19:16 UTC, jonatasmateus commented on src/main/java/com/uniprojecao/fabrica/gprojuridico/utils/Utils.java
> -    public static <T> Map<String, Object> filterValidKeys(Map<String, Object> inputMap, Class<T> clazz) {
O método deve permanecer no back, ao menos que haja garantia que o front-end não envie corpo de dados com algumas chaves inválidas.

2024-10-24 19:18 UTC, jonatasmateus commented on src/main/java/com/uniprojecao/fabrica/gprojuridico/utils/Utils.java
> -    private static Map<String, Object> processNestedKeysIntoOne(Map<String, Object> inputMap) {
Esses métodos de processar chaves de objetos que contém outros objetos dentro de si devem permanecer para fazer a correta inserção/atualização do objeto no Firestore.

2024-10-24 19:18 UTC, jonatasmateus commented on src/main/resources/application.properties
> +# GPC
Corrigir comentário GPC para GCP.

2024-10-24 19:24 UTC, jonatasmateus commented on src/main/java/com/uniprojecao/fabrica/gprojuridico/dto/body/UpdateBodyDTO.java
> +public class UpdateBodyDTO<T> {
Faltou haver o modificador de acesso `private` nos campos da classe para assegurar que qualquer classe que instanciar esta classe faça apenas uso dos métodos desta.

2024-10-24 19:27 UTC, jonatasmateus commented on src/main/java/com/uniprojecao/fabrica/gprojuridico/repositories/FirestoreRepositoryImpl.java
> -        Object lastDoc = "Not available";
A inicialização destas duas variáveis foi realizada para evitar que uma exceção seja lançada quando uma das duas seja null. Ou seja, é preciso avaliar e implementar uma solução que assegure que a exceção não seja lançada quando o(s) objeto(s) é null.

2024-10-24 19:28 UTC, jonatasmateus commented on src/main/java/com/uniprojecao/fabrica/gprojuridico/repositories/FirestoreRepositoryImpl.java
> +        T lastDoc = docPage.isEmpty() ? null : docPage.get(docPage.size() - 1);
Ler comentário ao lado ou anterior sobre deixar a(s) variável(s) `firstDoc` e `lastDoc` inicializadas.

2024-10-24 19:29 UTC, jonatasmateus requested changes
Revisão realizada; necessário alguns poucos ajustes apenas, @RafaelAguiarRodrigues

2024-10-27 14:33 UTC, RafaelAguiarRodrigues commented on src/main/java/com/uniprojecao/fabrica/gprojuridico/repositories/FirestoreRepositoryImpl.java
> +        firestore.collection(collectionName).document(recordId).update(data);
Adicionado as verificações jakarta validations via "@Valid"

2024-10-27 14:34 UTC, RafaelAguiarRodrigues commented on pom.xml
> +        <!-- JUnit 5 -->
removida

2024-10-27 14:35 UTC, RafaelAguiarRodrigues commented on src/main/java/com/uniprojecao/fabrica/gprojuridico/utils/Utils.java
> -    public static <T> Map<String, Object> filterValidKeys(Map<String, Object> inputMap, Class<T> clazz) {
Como citado no comentário da repository, foi adicionado "@Valid" na controladora e no body de edição para verificar as classes e seus atributos

2024-10-27 14:36 UTC, RafaelAguiarRodrigues commented on src/main/resources/application.properties
> +# GPC
Renomeado com sucesso

2024-10-27 14:37 UTC, RafaelAguiarRodrigues commented on src/main/java/com/uniprojecao/fabrica/gprojuridico/dto/body/UpdateBodyDTO.java
> +public class UpdateBodyDTO<T> {
Corrigido, adicionado o modificador **private** para os atributos

2024-10-27 14:50 UTC, RafaelAguiarRodrigues commented on src/main/java/com/uniprojecao/fabrica/gprojuridico/repositories/FirestoreRepositoryImpl.java
> -        Object lastDoc = "Not available";
Tratamento para objetos nulos restaurado

2024-10-28 18:15 UTC, RafaelAguiarRodrigues commented on src/main/java/com/uniprojecao/fabrica/gprojuridico/utils/Utils.java
> -    private static Map<String, Object> processNestedKeysIntoOne(Map<String, Object> inputMap) {
Foi testado um update em um assistido trabalhista via postman e não foi detectado nenhum erro do registro no firebase e nem durante as requisições (atualização e consulta), o objeto provavelmente está sendo mapeado corretamente devido o formato da classe ser passada para os métodos genéricos antes  da conversão pra map e sendo salvo no banco, fora que as controllers possuem validação para formato do objeto.

2024-10-30 20:19 UTC, jonatasmateus commented on src/main/java/com/uniprojecao/fabrica/gprojuridico/repositories/FirestoreRepositoryImpl.java
> +        firestore.collection(collectionName).document(recordId).update(data);
Os validadores do Jakarta mostraram funcionar e evitar que campos não pertencentes à classe sejam adicionados ao banco, exceto o @ type, conforme imagem a seguir:

![T1 - @type visivel e campos null setados](https://github.com/user-attachments/assets/e122ee5d-d4c0-42bc-a7b4-5b2c23ea93f2)

Além disso, se um objeto for passado com alguns campos ao invés de todos os campos, os demais campos são definidos como null (normal ser assim), entretanto são aceitos e vão para banco, constituindo assim uma vulnerabilidade na integridade dos dados.

## Ajustes a Realizar

Elaborar lógica para:

1. Remover o campo @ type no método de update
2. Remover campos que estejam null

2024-10-30 20:22 UTC, jonatasmateus commented on src/main/java/com/uniprojecao/fabrica/gprojuridico/utils/Utils.java
> -    private static Map<String, Object> processNestedKeysIntoOne(Map<String, Object> inputMap) {
@RafaelAguiarRodrigues, favor verificar comentário feito no arquivo FirestoreRepositoryImpl.java para tratar a adição do campo @ type e de campo com valor null no método update.

2024-10-30 20:25 UTC, jonatasmateus commented on src/main/java/com/uniprojecao/fabrica/gprojuridico/dto/body/UpdateBodyDTO.java
> +public class UpdateBodyDTO<T> {
Necessário adicionar também o decorador abaixo na classe para evitar que uma exceção de criação de classe sem construtor seja lançada (pois aconteceu comigo durante o teste):

```
// ...
@NoArgsConstructor
public class UpdateBodyDTO<T> { ... }
```

2024-11-09 17:36 UTC, RafaelAguiarRodrigues commented on src/main/java/com/uniprojecao/fabrica/gprojuridico/dto/body/UpdateBodyDTO.java
> +public class UpdateBodyDTO<T> {
Corrigido adicionado a anotação @NoArgConstructor

2024-11-09 17:48 UTC, RafaelAguiarRodrigues commented on src/main/java/com/uniprojecao/fabrica/gprojuridico/utils/Utils.java
> -    private static Map<String, Object> processNestedKeysIntoOne(Map<String, Object> inputMap) {
adicionado o tratamento na service para remover o campo `@type` durante edição

2024-11-09 17:50 UTC, RafaelAguiarRodrigues commented on src/main/java/com/uniprojecao/fabrica/gprojuridico/repositories/FirestoreRepositoryImpl.java
> +        firestore.collection(collectionName).document(recordId).update(data);
provisoriamente o front está mandando todos os dados e caindo dentro da verificação do `@Valid`, posteriormente alterar para somente os campos desejados

2024-11-19 15:18 UTC, merged